### ISSUE TITLE
ImportError with html5lib on v0.3.1

### ISSUE THREAD

**Issue by cletomartin** [python-mechanize/mechanize#1]
Looks like `html5lib` has been introduced as a depency at: https://github.com/python-mechanize/mechanize/commit/75f3690d12b793e05fc118b9944c6753a0dc8a7a

This is easy to reproduce:

```
>>> import mechanize
>>> br = mechanize.Browser()
>>> br.open('https://example.com')
>>> br.select_form('whatever')
```
An easy workaround is just to install the missing library with: `pip install html5lib`. However, I would expect that such internal dependency would be already installed along mechanize.

What about adding the following to `setup()` at `setup.py`?

```
install_requires=['html5lib']
```
Or with a fix version:

```
install_requires=['html5lib==0.999999999']
```

**Comment by kovidgoyal** [comment]
html5lib is already in requirements.txt which pip should process autoamtically.

**Comment by kovidgoyal** [comment]
Rather than depend on pip, I changed requirements.txt to use install_requires instead, which should take care of it.

**Comment by cletomartin** [comment]
Right. Thanks.
