### ISSUE TITLE
ImportError: cannot import name ParseResponse

### ISSUE THREAD

**Issue by tim-hub** [python-mechanize/mechanize#10]
when I
`
from mechanize import ParseResponse, urlopen, urljoin
`

**Comment by tim-hub** [comment]
python 2.7.12

**Comment by kovidgoyal** [comment]
There is no ParseResponse any more. All parsing is done via html5lib. See the changelog.

**Comment by tim-hub** [comment]
thanks for your so soon reply. I think maybe editing the examples will help new users a lot

**Comment by tim-hub** [comment]
Another question, can you show me how can I replace ParseReponce of html5lib?

**Comment by kovidgoyal** [comment]
https://mechanize.readthedocs.io/en/latest/

**Comment by tim-hub** [comment]
thanks

**Comment by madmashup** [comment]
The html5lib doesn't return the same object ParseResponse used to!
