### ISSUE TITLE
Feeding some URL to Browser.open() ends up in UnicodeDecodeError

### ISSUE THREAD

**Issue by xor512** [python-mechanize/mechanize#11]
Trying to execute this code:

```
browser = mechanize.Browser()
browser.set_handle_robots(False)
browser.open('http://musicmp3spb.org/album/plays_the_sound_of_philadelphia_a_tribute_to_kenny_gamble_leon_huff.html')
```

leads to UnicodeDecodeError. Ths link is up and running just click at http://musicmp3spb.org/album/plays_the_sound_of_philadelphia_a_tribute_to_kenny_gamble_leon_huff.html.I believe this has something ton do with this issue:

http://bugs.python.org/issue11898 

but applying a patch from it to httplib (http://bugs.python.org/file21747/python-2.7.1-fix-httplib-UnicodeDecodeError.patch) did not help.

Also this advice: https://stackoverflow.com/questions/1525295/how-to-fix-encoding-in-python-mechanize (the last one about _factory) was of no help either. I believe the problem is that part of what this page returns is cp1251 a Mechanize thinks is utf-8 or even ascii. How can I fix that? Is there a way to explicitely say Mechanize that this page is in that encoding? There is no Mechanize available for Python 3 so I cannot fix that just by switcing Python version. Would have to go to Beuatiful Soup instead but Mechanize is simpler for my needs so I would really prefer to stick to it.

Can you help with this annoying bug? Here some more description on my page where I use mechanize to scramble songs: https://github.com/xor512/musicmp3spb.org/issues/1

**Comment by kovidgoyal** [comment]
Simply call

browser.set_handle_refresh(False)
browser.set_handle_equiv(False)

before doing open()

**Comment by kovidgoyal** [comment]
Actually I dont hink you need browser.set_handle_refresh(False) either. Just set_handle_equiv(False)

**Comment by xor512** [comment]
Finally! It helped! Thank you very much.

**Comment by xor512** [comment]
PS Can you explain why was this happening and why sete_handle_equiv(False) helped?

**Comment by liamkirsh** [comment]
Thanks for the fix!
