### ISSUE TITLE
<input name="a" value/> gets interpreted wrongly

### ISSUE THREAD

**Issue by rubdos** [python-mechanize/mechanize#12]
`<input name="a" value/>` gets interpreted as `<input name="a" value="value"/>`. Is this desired behaviour?

I agree it is an erratic `<form>`, but I think it's more logical to interpret it as an empty `value` rather than as a `value="value"`

**Comment by kovidgoyal** [comment]
I cannot reproduce:

```sh
python2 -c "import mechanize; open('/tmp/f.html', 'w').write('<form><input name="a" value/>'); br = mechanize.Browser(); br.open('file:///tmp/f.html'); br.select_form(nr=0); print(repr(br['a']))"         
u''
```

**Comment by rubdos** [comment]
Weird. I'll check how this happened then. I got a form that gets all fields with that notation set with "value=value".

**Comment by rubdos** [comment]
Seems like this program is using mechanize 0.2.5. Case closed until further notice.
