### ISSUE TITLE
TypeError: parse() got an unexpected keyword argument 'transport_encoding'

### ISSUE THREAD

**Issue by connerpaulge** [python-mechanize/mechanize#17]
Hi!

I am trying to use mechanize to automate logging into a webpage but I have been stuck on this issue for a few days now.  I keep getting the TypeError listed above.  I have tried upgrading html5lib with no avail.

This is my code:
import mechanize
browser = mechanize.Browser()
browser.set_handle_robots(False)
cookies = mechanize.CookieJar()
browser.set_cookiejar(cookies)
browser.addheaders = [('User-agent', 'Mozilla/5.0 (X11; U; Linux i686; en-US) AppleWebKit/534.7 (KHTML, like Gecko) Chrome/7.0.517.41 Safari/534.7')]
browser.set_handle_refresh(False)

url = 'http://www.facebook.com/login.php'
browser.open(url)
browser.select_form(nr = 0)       #This is login-password form -> nr = number = 0
browser.form['email'] = YourLogin
browser.form['pass'] = YourPassw
response = self.browser.submit()
print response.read()

I really need this to work for a project so any help will be greatly appreciated!!!!

Thanks
Conner

**Comment by kovidgoyal** [comment]
That error comes from having a version a html5lib that is too old.

**Comment by connerpaulge** [comment]
Like I said I tried to upgrade html5lib and it didnt work.  Any other solution?
