### ISSUE TITLE
Mechanize method run with multiple url like different websites

### ISSUE THREAD

**Issue by shashiRS** [python-mechanize/mechanize#19]
I am Using Mechanize library in python. I am running script multiple websites it should find the form and submit it with automatically. first,i'am facing problem in fetching name attribute value automatically and fill the data and send it. This have select type it should select automatically. second, there is no form present in that contact form how to fill the data and submit it?.

please help me

**Comment by kovidgoyal** [comment]
An issue tracker is not an appropriate place to ask for help.
