### ISSUE TITLE
Allow JSON as a valid response type

### ISSUE THREAD

**Issue by erichydrick** [python-mechanize/mechanize#2]
Useful when trying to test REST services. This flag should default to False for backwards compatibility.

**Comment by kovidgoyal** [comment]
I'm not sure I understand the use case for this? The whole point of mechanize is to behave like a browser, which means making it easy to fill forms/follow links/handle cookies/handle redirects/etc. None of that is needed for REST APIs. Why use mechanize at all for that? Use plain urllib2 or requests. 

Also the proper approach for this is not to detect JSON as HTML, which may break things elsewhere in the stack. Instead you should add handling for JSON separately in the set_resnpose() method of the Factory class and then add a separate function named something like get_json() to the Browser class that will return JSON, if available.

**Comment by erichydrick** [comment]
Since this is out of scope I'll close the issue then.
