### ISSUE TITLE
Keep BeautifulSoup4 parser option, probably as a parameter to mechanize.Browser()

### ISSUE THREAD

**Issue by liangent** [python-mechanize/mechanize#20]
I found breakage on some existing script after upgrading mechanize from 0.2.5 to the latest version. `git bisect` led me to 75f3690d12b793e05fc118b9944c6753a0dc8a7a and it seems that particular web page can't be parsed correctly with html5lib. I have no control over that web page and I know it's pretty old in terms of web standards used, but BS4 seems to have better compatibility with it. I feel there can be more websites/pages in this category.

**Comment by kovidgoyal** [comment]
I'm afraid not. bs4 has a pretty bad parsing algorithm, it matches no browser behavior and no standard and has its own unique semantics.

**Comment by liangent** [comment]
Alright you mentioned "browser behavior" and it seems you have better understanding of web page parsing than me as you're maintaining https://github.com/kovidgoyal/html5-parser . So let me show the problematic page to you:

I put a stripped down version of the original page at http://bxp.d.liangent.com/~liangent/mechanize-test.html , basically there's a <form> tag between <table> and <tr> which might be the issue but I'm not sure. I'm testing it with this script:

```
#!/usr/bin/env python

import mechanize

br = mechanize.Browser()

br.open('http://bxp.d.liangent.com/~liangent/mechanize-test.html')
br.select_form(name='form1')

print br.form.controls
```

With the current version of mechanize (tested in b7f10602a26deabcac835e4a22542628444f6544), it shows no control in the form. With an older version using BS4 (tested in 2d44754), there're three controls in the form. In Chrome (tested in Chromium Version 63.0.3239.84), if you try to submit the form, you can see that values of all three controls are submitted in the query string, though in developer tool, those controls seem to be outside the form.

**Comment by kovidgoyal** [comment]
They are outside the form. So if you want to submit them in mechanize, IIRC you have to use the "global form". BS4 incorrectly puts them inside the form. html5lib and the browser (as evidenced by the developer tools) correctly put them outside the form.

**Comment by liangent** [comment]
Using global form missed the specified method/action in form1, while Chrome correctly submits the (global?) form to mechanize-submit.html (this is the behavior I want to see but I'm not sure why Chrome is doing this).

**Comment by kovidgoyal** [comment]
The browsers probably have some logic to use the previous <form> when submitting a control outside any forms. You could probably add that to mechanize as well -- not something I am interested in personally, but patches are welcome.

**Comment by liangent** [comment]
That's not the browser logic.. I tested http://bxp.d.liangent.com/~liangent/mechanize-test-2.html where those controls are put outside the form "explicitly" and neither Chrome nor Firefox submits the form (the "Login" button does no action at all).

**Comment by kovidgoyal** [comment]
In that case you will need to read the browser source code to figure out its logic. That's rather a lot of work. Might be simpler to just change your script to use the action from the form explicitly. And feel free to edit the title fo the bug report.

**Comment by kovidgoyal** [comment]
And here's the relvant section of the spec: https://www.w3.org/TR/html51/sec-forms.html#sec-constructing-the-form-data-set

**Comment by kovidgoyal** [comment]
Sorry, that should be: https://www.w3.org/TR/html51/sec-forms.html#form-owner

In particular:
```
The rules in this section are complicated by the fact that although conforming documents will never contain nested form elements, it is quite possible (e.g., using a script that performs DOM manipulation) to generate documents that have such nested elements. They are also complicated by rules in the HTML parser that, for historical reasons, can result in a form-associated element being associated with a form element that is not its ancestor.
```

**Comment by liangent** [comment]
It seems the browser did some hack to set the form owner of those controls to form1 during HTML parsing (confirmed with `document.getElementById('user').form`), probably for compatibility. Does mechanize generally follow these hacks?

**Comment by kovidgoyal** [comment]
When feasible it tries to follow browser behavior. In this case it is not really feasible, as this hack would have to be implemented in the html parser, deviating from the spec.
