### ISSUE TITLE
Cant set `host` header

### ISSUE THREAD

**Issue by LawYard** [python-mechanize/mechanize#4]
Hi!

Trying to set http header `host` when using `Browser`, but its not work!

```py
import mechanize


b = mechanize.Browser()
b.set_handle_robots(False)
addheaders = [('Test-Header', 'Test'),
              ('Host', 'test.local')]

b.addheaders = addheaders

b.open('http://localhost:1024/')
```

In my localhost I run the following:

```sh
nc -l 1024
```

Then start my python code and get:

```
GET / HTTP/1.1
Accept-Encoding: identity
Host: localhost:1024
Connection: close
Test-Header: Test
```

Why `Host` is equal `localhost:1024`? :(

My env:

MacOS
Mechanize Version: 0.3.1

**Comment by kovidgoyal** [comment]
IIRC in mechanize to change request specific headers such as Host, one has to use a custom request (Not being the original developer of mechanize, I can't say why it was designed that way). See for example the test_add_host_header() function in test_browser.py

Probably something worth changing

**Comment by LawYard** [comment]
Thats really worked for me))

```py
import mechanize


b = mechanize.Browser()
b.set_handle_robots(False)

request = mechanize.Request("http://localhost:1024/")
request.add_header("Host", "test.local")

b.open(request)
```

Result:

```
GET / HTTP/1.1
Accept-Encoding: identity
Host: test.local
Connection: close
User-Agent: Python-urllib/2.7
```

It looks weird, but works :)

Do u want to fix that in future releases? I mean - do I need to close issue?

**Comment by LawYard** [comment]
Yeah! Thx for fix 👍
