### ISSUE TITLE
Adding a new control without index makes the submit fail

### ISSUE THREAD

**Issue by mrodal** [python-mechanize/mechanize#40]
When adding a new control without an index and then submitting, it throws 

`TypeError: '<' not supported between instances of 'NoneType' and 'int'`

on the `pairs.sort()` on `_pairs_and_controls` on `_forms_controls.py`.

Maybe the fixup should set some index if none is set?

**Comment by kovidgoyal** [comment]
Can you post a minimal test script to reproduce the error.

**Comment by mrodal** [comment]
This doesnt work
```
import mechanize
br=mechanize.Browser()
br.open('https://mechanize.readthedocs.io')
br.select_form(id='rtd-search-form')
br.form.new_control('hidden', 'newcontrol', {})
br.form.fixup()
br.submit()
```

But adding any index to the `new_control` call makes it work, for example 
`br.form.new_control('hidden', 'newcontrol', {}, index=199)`
