### ISSUE TITLE
Zip File Upload As part of Online Form

### ISSUE THREAD

**Issue by dexman545** [python-mechanize/mechanize#44]
Attempting to upload a zip file as part of a form with other selections. Having tried various inputs to br.form.add_file(), python still spits out an error. Also unsure if I need to provide the name/id of the upload portion of the form.

Tried loading the zip with ZipFile and passing that directly to the upload function, also tried providing MIME type and upload file name.

`br.select_form(id='upload_form')
print('Supplying Text...')
br['chapter_name'] = 'test'
br['chapter_number'] = '55'
zip = zips / '16x16.zip'
#with ZipFile(zip, 'r') as zip:
br.form.add_file(open(zip))
print('Submitting form...')
response = br.submit()

Current setup provides this error: 'charmap' codec can't decode byte 0x9d in position 199: character maps to <undefined>`

Python 3.7
Mechanize 0.42

**Comment by kovidgoyal** [comment]
It would help if you posted the full error, including the traceback and
also what webpage you are connecting to so I can try to reproduce.

**Comment by dexman545** [comment]
I am unsure of what changed, but I no longer get an error when trying to upload, though the upload is still unsuccessful.
Attempting to upload here: https://mangadex.org/upload/47 (a dummy manga for testing purposes), if successful should have a chapter appear here: https://mangadex.org/title/47

Code:
import re
import mechanize
from pathlib import Path
from zipfile import ZipFile
import requests


br = mechanize.Browser()

# Ignore robots.txt
br.set_handle_robots( False )
# Google demands a user-agent that isn't a robot
br.addheaders = [('User-agent', 'Firefox')]
print('Logging in...')

br.open('https://mangadex.org/login')
br.select_form(id="login_form")
br['login_username'] = '*********'
br['login_password'] = '*************'
br.submit()
print('Logged in')

zips = Path('ProcessData/zips')
rawsB = Path('ProcessData')
rawsB.mkdir(parents=True, exist_ok=True)


m = rawsB / 'debug.txt'

try:
    response = br.open('https://mangadex.org/upload/47')
    br.select_form(id='upload_form')
    print('Supplying Text...')
    br.set_all_readonly(False)
    br['chapter_name'] = 'testy'
    br['chapter_number'] = '33'
    zip = zips / 'test.zip'
    #with ZipFile(zip, 'r') as zip:
    br.form.add_file(open(zip, 'rb'))
    print('Submitting form...')
    r = br.submit()
    m.write_text(str(r.read()))
except mechanize.HTTPError as e:
    print(e)
    print(e.code)

**Comment by kovidgoyal** [comment]
And I see no rendering issues with lambda and dejavu sans mono with adjust_line_height=20:

```
kitty --config NONE -o font_family=DejaVu\ Sans\ Mono -o adjust_line_height=20
```

![Screenshot_20190617_093343](https://user-images.githubusercontent.com/1308621/59577917-53d5b080-90e3-11e9-93f6-56127a32f915.png)

**Comment by kovidgoyal** [comment]
Hard for me to say, since I dont have access to that server, but try setting the content tye and filename by using the content_type and filename arguments to add_file() 

Probably the server needs one or both of those to process the file upload.
