### ISSUE TITLE
http-equiv="refresh" HTML Meta Tag Form Parse Error 

### ISSUE THREAD

**Issue by umit-ozturk** [python-mechanize/mechanize#46]
Hi everyone,

I' using this library. I have a bug. I parse the forms of the site but when the site has <meta http-equiv="refresh" content="x" />  tag, form or forms cannot be found.

Example;

```
<html>
<head>
  <meta http-equiv="refresh" content="300" />
</head>
<body>
  <form action="#" method="POST">

    <input type="email">
    <input type="password" name="pass">
    <input type="submit" value="Submit">
  </form>
</body>
</html>
```
Its my html code.

I'm using this parameter.

        browser = mechanize.Browser()

        browser.set_handle_robots(False)

        browser.set_handle_equiv(True)

        browser.set_handle_redirect(True)

        browser.set_handle_refresh(mechanize._http.HTTPRefreshProcessor(), max_time=1)

        browser.addheaders = [('User-agent', 'Mozilla / 5.0 (Windows NT 6.1) AppleWebKit / 537.36(KHTML, '
                               'like Gecko) Chrome / 41.0.2228.0 Safari / 537.36')]

after that.

```
browser.open(site_url)
print(browser.forms())
```

>  []

Actually, I've tried many browser parameter but I couldn't parse forms this meta tag.

**Comment by kovidgoyal** [comment]
Turn off set_handle_equiv() and set_handle_refresh() and you should be fine.
