### ISSUE TITLE
Python3 support information (project site and pypi metadata) can be updated

### ISSUE THREAD

**Issue by futu** [python-mechanize/mechanize#49]
According to https://mechanize.readthedocs.io/en/latest/faq.html#which-version-of-python-do-i-need python3 isn't supported. 

Release notes says about python3 support and pypi.org json has record about python 3 support in latest versions.
`
'0.4.3': [
      {
        'comment_text': '',
        'digests': {
          'md5': '3cac491b19435ae1f761af330c4bbe95',
          'sha256': '4e8a7703bef5d43b5c753e64e27451b4e66fdc32554b31f5563ad1a82f3142bc'
        },
        'downloads': -1,
        'filename': 'mechanize-0.4.3-py2.py3-none-any.whl',
        'has_sig': True,
        'md5_digest': '3cac491b19435ae1f761af330c4bbe95',
        'packagetype': 'bdist_wheel',
        'python_version': 'py2.py3',
        'requires_python': None,
        'size': 107969,
        'upload_time': '2019-08-18T08:08:20',
        'url': 'https://files.pythonhosted.org/packages/bc/68/5ab6f96dfbdae2182e214cf9cc4790f2810c695c04034cc067b0e4ffa2b7/mechanize-0.4.3-py2.py3-none-any.whl'
      },
`

But classifiers field doesn't have python3 in 'Programming Language' section.

Adding 'Programming Language :: Python :: 3.7' will be helpful while searching on Pypi.org.

**Comment by kovidgoyal** [comment]
The classifiers does have Programming Language :: Python

I dont want to stick specific versions in there, I will never remember
to update them.
