### ISSUE TITLE
Missing RobustFactory

### ISSUE THREAD

**Issue by Nandaka** [python-mechanize/mechanize#5]
Looks like the 3.x version doesn't have ```RobustFactory``` anymore?

```
...
    mechanize.Browser.__init__(self, factory=mechanize.RobustFactory())
AttributeError: 'module' object has no attribute 'RobustFactory'
```

https://github.com/Nandaka/PixivUtil2/issues/218

**Comment by kovidgoyal** [comment]
Yes, as per the Changelog, mechanize.Browser does not accept the factory argument anymore. All HTML parsing is done using html5lib.
