### ISSUE TITLE
Requesocks and mechnize not working

### ISSUE THREAD

**Issue by dzimbeck** [python-mechanize/mechanize#53]
Hi so when I use mechanize on its own using python 2.711 everything works. However when I import requesocks then I get this error when trying to submit a form:

  File "C:\Python27\lib\site-packages\html5lib\_inputstream.py", line 4, in <mod
ule>
    from six.moves import http_client, urllib
ImportError: cannot import name urllib

This makes it harder to use proxies in other parts of my code without monkey patching everything with pysocks. That's why I like to use requesocks but it seems the libraries conflict. It would be nice if mechanize had socks support for TOR.

**Comment by kovidgoyal** [comment]
Install html5-parser then mechanize will use and it has no dependency on
six.
