### ISSUE TITLE
TypeError: parse() got an unexpected keyword argument 'transport_encoding'

### ISSUE THREAD

**Issue by wookienz** [python-mechanize/mechanize#6]
mechnize 0.3.1
html5lib .999

 TypeError: parse() got an unexpected keyword argument 'transport_encoding'

what ver of html5lib is mechanize built on?

v 0.999 is:
def parse(doc, treebuilder="etree", encoding=None, namespaceHTMLElements=True)

v 0.99999999:
def parse(doc, treebuilder="etree", namespaceHTMLElements=True, **kwargs)

I think this is the issue.

**Comment by wookienz** [comment]
reinstalled v 0.9 x 8 confirmed working.

**Comment by kovidgoyal** [comment]
Yes, you need a new enough version of html5lib -- I haven't bothered checking exactly which one, all those nines make me dizzy.

**Comment by colinwxl** [comment]
I still could not solve it. can you offer any solution?

**Comment by nishankmahore** [comment]
conda install --force html5lib fixed the problem for me.
