### ISSUE TITLE
How to parse forms from a string?

### ISSUE THREAD

**Issue by guettli** [python-mechanize/mechanize#61]
What is the official way to parse the forms from a string?

I think this would be a good new entry in the "Forms" section of the [FAQ](https://mechanize.readthedocs.io/en/latest/faq.html#forms)

Related: https://stackoverflow.com/questions/65570418/django-parse-html-containing-form-to-dictionary

**Comment by kovidgoyal** [comment]
There is no official API, forms are tied to browser objects, since they
need information such as encoding, base url, etc. If you really want,
you can do it with

```py
from mechanize._form import parse_forms
from mechanize._html import content_parser

url = 'http://whatever.com'
data = '<html>....'
root = content_parser(data, url)
forms, global_form = parse_forms(root, url)
```
