### ISSUE TITLE
Cannot select <input> tag

### ISSUE THREAD

**Issue by Zawszy** [python-mechanize/mechanize#63]
I have been running browser.select_form("search") in an attempt to select an input tag with name search but this does not work. Is there a way to do this in Mechanize? Thank you.

**Comment by kovidgoyal** [comment]
select_form() selects *forms*. If your input tag doesnt belong to any
form then it will be part of the global form.

**Comment by Zawszy** [comment]
> select_form() selects _forms_. If your input tag doesnt belong to any
> form then it will be part of the global form.

Could you run me through selecting <input> if not part of form? Could not find any information regarding this online

**Comment by kovidgoyal** [comment]
form = br.global_form()
form['name'] = whatever

**Comment by Zawszy** [comment]
> form = br.global_form()
> form['name'] = whatever

Sorry for the questions but this does not seem to work for this webpage: https://promedmail.org/promed-posts/
(trying to get the second search bar).

I get the following output when attempting to print the global form:  
  <IgnoreControl(<None>=<None>)>
  <IgnoreControl(<None>=<None>)>
  <IgnoreControl(<None>=<None>)>>

Does this mean there is no way to access the <input> (second search bar) with Mechanize?
