### ISSUE TITLE
Browser excluding form control

### ISSUE THREAD

**Issue by Phytal** [python-mechanize/mechanize#65]
I am trying to access the `__EVENTTARGET` control as shown below, which is the page source code from my local browser

```
<div id='MainContent' class='sg-main-content'>
    <div class='sg-hac-content'>
        <form method="post" action="./Assignments.aspx" id="fmMain">
              <div class="aspNetHidden">
                 <input type="hidden" name="__EVENTTARGET" id="__EVENTTARGET" value="" />
                 <input type="hidden" name="__EVENTARGUMENT" id="__EVENTARGUMENT" value="" />
                 <input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="val" />
              </div>
```

However when Browser opens this exact same page the HTML is different.
`br.open(link).read()`

```
<div id='MainContent' class='sg-main-content'>     
  <div class='sg-hac-content'>  
    <form method="post" action="./Assignments.aspx" id="fmMain"> 
      <input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="val" />
      <input... (goes onto the next set of controls)/>
```

I think the value attribute being empty is a possible cause. Should this be happening and is there a workaround for this?

**Comment by kovidgoyal** [comment]
post an actual full HTML document that is incorrectly parsed.

**Comment by Phytal** [comment]
Here are the full HTML documents:
[Page Source](https://gist.github.com/Phytal/a69c890d64ce731ffba3ee3826d0b9bf)
[Browser](https://gist.github.com/Phytal/2134cd03de694183cb6df80875246274)

**Comment by kovidgoyal** [comment]
Works for me:
```
python -c "from mechanize import Browser; br = Browser(); br.open('http://localhost:8000/original.html'); br.select_form(nr=0); print(repr(br['__EVENTTARGET']))"   
''
```

prints the empty string, as expected given that form value is empty.

**Comment by Phytal** [comment]
That's strange. I tried out doing what you did (hosting html on local host) and it worked, however when I ran it with my link it returned `mechanize._form_controls.ControlNotFoundError: no control matching name '__EVENTTARGET'`. It seems to me that Browser is reading a different HTML than the page source than I am (Browser read [this](https://gist.github.com/Phytal/2134cd03de694183cb6df80875246274)). Do you have any idea why this is happening? Here is my code
```
    br = mechanize.Browser()

    # Browser options
    br.set_handle_equiv(True)
    br.set_handle_gzip(True)
    br.set_handle_redirect(True)
    br.set_handle_referer(True)
    br.set_handle_robots(False)
    br.set_handle_refresh(mechanize._http.HTTPRefreshProcessor(), max_time=1)
    br.addheaders = [('User-agent', 'Chrome')]

    br.open('https://' + link + '/HomeAccess/Account/LogOn?ReturnUrl=%2fHomeAccess/Classes/Classwork%2f')

    br.select_form(nr=0)

    br['LogOnDetails.UserName'] = username
    br['LogOnDetails.Password'] = password

    br.submit() # log in

    default = br.open("https://" + link + "/HomeAccess/Content/Student/Assignments.aspx")
    # print(default)
    br.select_form(nr=0)

    print(repr(br['__EVENTTARGET'])) # returns error
```
The form objects contains [this html](https://gist.github.com/Phytal/c544d1a6805094364fa34ffd56e9e4cb), which does not contain `__EVENTTARGET`

**Comment by kovidgoyal** [comment]
There will be javascript or server side browser detection involved.

**Comment by Phytal** [comment]
So you're saying that this is because that the server/javascript detected that this isn't a legitimate user? Is there anything I could do about that?

**Comment by kovidgoyal** [comment]
yes and as for doing things about it, you will need to figure out what
the protection is and then work around it, mechanize wont do it for you.
