### ISSUE TITLE
mechanize._response.httperror_seek_wrapper: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by pabst2009** [python-mechanize/mechanize#69]
I try to run the following simple mechanize call.

    import mechanize;
    b=mechanize.Browser();
    b.set_handle_robots(False);
    url="https://finance.yahoo.com/quote/^DJI/history";
    h=b.open(url);

Then I got the following error.

    mechanize._response.httperror_seek_wrapper: HTTP Error 404: Not Found

The error disappeared when I replace the url as follows.

    url="http://google.com";

Is this an issue of mechanize or do I make a mistake?

I use Python 3.7.3 and mechanize 0.4.7.

**Comment by kovidgoyal** [comment]
That's an issue with the site. It responds with a 404.
```
curl -I 'https://finance.yahoo.com/quote/^DJI/history'                                                                                   
HTTP/2 404
```

It weirdly sends a normal html page as a response as well. Probably a misconfigured server.
