### ISSUE TITLE
mechanize 0.4.8 doesn't install correctly on raspberry pi

### ISSUE THREAD

**Issue by rabarberski** [python-mechanize/mechanize#76]
Installing mechanize 0.4.8 via pip on a raspberry pi running Debian Bullseye with python 3.9 doesn't as expected.
However, installing 0.4.7 is successful, so likely there is something missing in the 0.4.8 distribution package.

**Details (1)**: Installing mechanize with pip

    (venvtest) pi@mango:~/MyProject/myproj $ pip --version
    pip 20.3.4 from /home/pi/MyProject/myproj/venvtest/lib/python3.9/site-packages/pip (python 3.9)
    
    (venvtest) pi@mango:~/MyProject/myproj $ pip install mechanize
    Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
    Collecting mechanize
    Using cached https://www.piwheels.org/simple/mechanize/mechanize-0.4.8-py2.py3-none-any.whl (5.1 kB)
    Requirement already satisfied: html5lib>=0.999999999 in /home/pi/MyProject/myproj/venvtest/lib/python3.9/site-packages (from mechanize) (1.1)
    Requirement already satisfied: webencodings in /home/pi/MyProject/myproj/venvtest/lib/python3.9/site-packages (from html5lib>=0.999999999->mechanize) (0.5.1)
    Requirement already satisfied: six>=1.9 in /home/pi/MyProject/myproj/venvtest/lib/python3.9/site-packages (from html5lib>=0.999999999->mechanize) (1.16.0)
    Installing collected packages: mechanize
    Successfully installed mechanize-0.4.8

 
    (venvtest) pi@mango:~/MyProject/myproj $ pip list
    Package       Version
    ------------- -------
    html5lib      1.1
    mechanize     0.4.8
    pip           20.3.4
    pkg-resources 0.0.0
    setuptools    44.1.1
    six           1.16.0
    webencodings  0.5.1
    wheel         0.34.2

**Details (2)**: Package folder missing in sitelibs

    (venvtest) pi@mango:~/MyProject/myproj/ $ ls venvtest/lib/python3.9/site-packages
    easy_install.py            pip-20.3.4.dist-info            __pycache__                   six.py                        wheel
    html5lib                   pip-20.3.4.virtualenv           setuptools                    _virtualenv.pth               wheel-0.34.2.dist-info
    html5lib-1.1.dist-info     pkg_resources                   setuptools-44.1.1.dist-info   _virtualenv.py                wheel-0.34.2.virtualenv
    mechanize-0.4.8.dist-info  pkg_resources-0.0.0.dist-info   setuptools-44.1.1.virtualenv  webencodings
    pip                        pkg_resources-0.0.0.virtualenv  six-1.16.0.dist-info          webencodings-0.5.1.dist-info
   

**Details (3)**: As a consequence, importing mechanize doesn't work

    (venvtest) pi@mango:~/MyProject/myproj $ python
    Python 3.9.2 (default, Mar 12 2021, 04:06:34)
    [GCC 10.2.1 20210110] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import mechanize
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    ModuleNotFoundError: No module named 'mechanize'
    >>> exit()

See https://stackoverflow.com/a/72760801/50899

**Comment by kovidgoyal** [comment]
You are probably running pip from a different python than python 3.9

**Comment by rabarberski** [comment]
> You are probably running pip from a different python than python 3.9

I first thought so too, but I am 99% sure that's not the case. That's why I checked and included the `pip --version` output already in my ticket:

    (venvtest) pi@mango:~/MyProject/myproj $ pip --version
     pip 20.3.4 from /home/pi/MyProject/myproj/venvtest/lib/python3.9/site-packages/pip (python 3.9)

Also, why would mechanize 0.4.7 install successfully then?

**Comment by kovidgoyal** [comment]
In that case, it's probably caused by this https://github.com/python-mechanize/mechanize/pull/73  I'm afraid I dont have the time or interest to debug all the various permutations of shit that the python packaging ecosystem produces. The pull request is correct in that the new behavior matches the documented interface of setup.cfg. If the documented interface breaks with whatever packaging tools are present in your system, its a bug there.

 I suggest you simply cut pip out and download the source tarball, untar it and move the mechanize folder into site-packages yourself.

**Comment by rabarberski** [comment]
Fair enough; thanks for the reply.
