### ISSUE TITLE
Can't get redirection debugging with example code

### ISSUE THREAD

**Issue by barryrowlingson** [python-mechanize/mechanize#84]
I'm trying to get mechanize to log redirects, which I thought I could do with the logging and debugging methods.

This is basically the example code from the documentation:

```
import sys, logging
import mechanize

logger = logging.getLogger("mechanize.http_redirects")
logger.addHandler(logging.StreamHandler(sys.stdout))
logger.setLevel(logging.DEBUG)

browser = mechanize.Browser()
#browser.set_debug_http(True)
#browser.set_debug_responses(True)
browser.set_debug_redirects(True)
response = browser.open("http://httpstat.us/301")
```

Note it calls http://httpstat.us/301 which returns a 301 "Moved Permanently" redirect:

```
$ curl --include http://httpstat.us/301
HTTP/1.1 301 Moved Permanently
Content-Length: 21
Content-Type: text/plain
Date: Fri, 12 May 2023 16:55:23 GMT
Server: Kestrel
Location: https://httpstat.us
Set-Cookie: ARRAffinity=ec6b9b8199d9706949615f2545eaa0e05e03833e70e6ed4953d141913856cd3a;Path=/;HttpOnly;Domain=httpstat.us
Request-Context: appId=cid-v1:3548b0f5-7f75-492f-82bb-b6eb0e864e53
```

But the code doesn't log anything:

```
$ python log.py 
$
```
I've tried enabling the http and responses debugging (commented out above), and that does produce output, which shows `mechanize` is following the redirect and doing two GETs, but `set_debug_redirects` seems to have no effect.

What I'm trying to actually achieve is to send a login form by a POST request and see if I get back a 302 redirecting to "/" (which indicates a successful long) or a 200 response which results in "/login"... But then I hit this debugging trouble. 

Have I missed something?

Possibly relevant:
```
mechanize==0.4.8
urllib3==2.0.2
requests==2.30.0
```

**Comment by kovidgoyal** [comment]
Works for me with:

```sh
python -c 'import sys, mechanize, logging; logger = logging.getLogger("mechanize.http_redirects"); logger.addHandler(logging.StreamHandler(sys.stdout)); logger.setLevel(logging.DEBUG); br = mechanize.Browser(); br.set_debug_redirects(True); br.open("http://httpstat.us/301");'

Output:
redirecting to https://httpstat.us
```
