### ISSUE TITLE
find_link does not take into consideration XPATH and/or aria-role=link

### ISSUE THREAD

**Issue by andreamoro** [python-mechanize/mechanize#88]
Both the aria-role=link and XPATH could help reach for additional links that are not necessarily declared as traditional HTML tags.
These are apparently not considered as part of your code base unless I am misinterpreting your code.

**Comment by andreamoro** [comment]
So, when you say match any predicate you mean I can say look also into a div used for making a link, but then what?
How you would click on it?

Do you mind providing a snippet, if time allows your end?

As for CSS selectors, either that or XPATH would work to exactly match an item.
Yet the question still remain, how do you click in fact do a new get in a link that is JS based?

**Comment by kovidgoyal** [comment]
Mechanize has no support for JS
