### ISSUE TITLE
Please correct the error in _urllib2_fork.py

### ISSUE THREAD

**Issue by nik0380** [python-mechanize/mechanize#90]
Hello!
On  Python 3.12.1 (_Fedora 39_) package **mechanize** (method **open**) throws an error about invalid keys.
Temporarily the problem can be solved like this:

```
def https_open(self, req):
        key_file = cert_file = None
        if self.client_cert_manager is not None:
            key_file, cert_file = self.client_cert_manager.find_key_cert(
                req.get_full_url())
        if self.ssl_context is None:
            conn_factory = partial(
                HTTPSConnection #, key_file=key_file, cert_file=cert_file
                )
        else:
            conn_factory = partial(
                HTTPSConnection, # key_file=key_file, cert_file=cert_file,
                 context=self.ssl_context)
        return self.do_open(conn_factory, req)  
```

Please correct the error in _urllib2_fork.py

**Comment by kovidgoyal** [comment]
You are using an outdated version of mechanize, update.

**Comment by nik0380** [comment]
Thanks for your reply! I tried installing the latest version 0.4.9 and 0.4.8 (with pip). There was always the same error: the keys key_file and cert_file are deprecated.

**Comment by kovidgoyal** [comment]
Then you arent actually running the version you installed.

**Comment by nik0380** [comment]
Many thanks for the help! I checked it in a clean virtual environment - everything works!
