### ISSUE TITLE
403 Forbidden error (no mention of robots.txt however)

### ISSUE THREAD

**Issue by ValonVN0** [python-mechanize/mechanize#98]
Good Afternoon,

Haven't touched this project in a while however booting up and finding it's immediately dropping
```mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 403: Forbidden```

Which typically is due to the robots.txt however there seems to be no mention of this, and I did actually end up adding this way back when I WAS getting that issue

```br.addheaders = [('User-agent', 'Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.1) Gecko/2008071615 Fedora/3.0.1-1.fc9 Firefox/3.0.1')]```

Just wondering if I'm missing anything painfully obvious, as I've confirmed the URL is correct, I can connect to it manually via my usual browsers, so not sure if it's just outright blocking all access or?

**Comment by kovidgoyal** [comment]
It will most likely be because the server is implementing bot detection
based on heuristics or javascript or SSL handshake or similar.
