### ISSUE TITLE
Consider making a 1.0 release

### ISSUE THREAD

**Issue by Kodiologist** [python-mechanize/mechanize#99]
This package is over 20 years old. I imagine the interface is fairly stable by now.

**Comment by Kodiologist** [comment]
> Why?

Signifying the stability of software in its version number makes dependency management a little easier. [Semantic Versioning](https://semver.org/) has a nice discussion of related issues.

**Comment by kovidgoyal** [comment]
I'm afraid I do not believe that the stability of something as complex
as software can be usefully communicated in a couple of numbers.

People need to write tests to verify functionality not assume that they
can willy nilly upgrade dependencies based on a version number.
Especially in a dynamic language like python.

That said, I dont mind bumping the version number but I am not going to
create a release just for that. And nowadays mechanize is in maintenance
mode which means bumping the major version number will actually give a
false impression of large changes when there are none.
